/**
 * The flat per-URL evidence rows `buildMeasurementEvidence` produced for
 * `answerEvidenceInput()` BEFORE evidence became one row per answer, captured
 * from the kernel at commit ee49638a.
 *
 * It is the published shape: the generated SDK and the MCP tool list both carry
 * it, so the derived list has to stay byte-identical to this. Do not regenerate
 * it from the current kernel — that would bless whatever drift it is meant to
 * catch. Rows in slot id, usage edge id, source URL order, exactly as
 * `prepareReport` sorts them.
 *
 * Note what is NOT here: `slot-loss` answered and cited nobody, so it has no
 * row at all. That absence is the gap the answer-level rows exist to show.
 */

import type { MeasurementAttributionEvidence } from '../src/measurement-report.js'

export const FLAT_EVIDENCE_BASELINE: readonly MeasurementAttributionEvidence[] = [
  {
    observationId: 'observation-gemini',
    expectedSlotId: 'slot-shared-gemini',
    executionId: 'exec-shared',
    usageEdgeId: 'edge-baseline',
    usageEdgeType: 'baseline',
    provider: 'gemini',
    queryText: 'roof coating near harbor',
    location: 'Harbor, EX',
    sourceUrl: 'https://northstar.example/locations/north',
    bridged: true,
    historical: true,
    evidenceComplete: true,
    classification: 'sibling',
    normalizedUrl: 'https://northstar.example/locations/north',
    matchedTargetIds: ['north'],
    matchedUrlIds: ['north-url'],
  },
  {
    observationId: 'observation-gemini',
    expectedSlotId: 'slot-shared-gemini',
    executionId: 'exec-shared',
    usageEdgeId: 'edge-harbor-shared',
    usageEdgeType: 'target',
    provider: 'gemini',
    queryText: 'roof coating near harbor',
    location: 'Harbor, EX',
    sourceUrl: 'https://northstar.example/locations/north',
    bridged: true,
    historical: true,
    evidenceComplete: true,
    classification: 'sibling',
    normalizedUrl: 'https://northstar.example/locations/north',
    matchedTargetIds: ['north'],
    matchedUrlIds: ['north-url'],
  },
  {
    observationId: 'observation-gemini',
    expectedSlotId: 'slot-shared-gemini',
    executionId: 'exec-shared',
    usageEdgeId: 'edge-north-shared',
    usageEdgeType: 'target',
    provider: 'gemini',
    queryText: 'roof coating near harbor',
    location: 'Harbor, EX',
    sourceUrl: 'https://northstar.example/locations/north',
    bridged: true,
    historical: true,
    evidenceComplete: true,
    classification: 'assigned',
    normalizedUrl: 'https://northstar.example/locations/north',
    matchedTargetIds: ['north'],
    matchedUrlIds: ['north-url'],
  },
  {
    observationId: 'observation-openai',
    expectedSlotId: 'slot-shared-openai',
    executionId: 'exec-shared',
    usageEdgeId: 'edge-baseline',
    usageEdgeType: 'baseline',
    provider: 'openai',
    queryText: 'roof coating near harbor',
    location: 'Harbor, EX',
    sourceUrl: 'https://challenger.example/compare',
    bridged: false,
    historical: false,
    evidenceComplete: true,
    classification: 'external',
    normalizedUrl: 'https://challenger.example/compare',
    matchedTargetIds: [],
    matchedUrlIds: [],
  },
  {
    observationId: 'observation-openai',
    expectedSlotId: 'slot-shared-openai',
    executionId: 'exec-shared',
    usageEdgeId: 'edge-baseline',
    usageEdgeType: 'baseline',
    provider: 'openai',
    queryText: 'roof coating near harbor',
    location: 'Harbor, EX',
    sourceUrl: 'https://northstar.example/locations/harbor/details',
    bridged: false,
    historical: false,
    evidenceComplete: true,
    classification: 'sibling',
    normalizedUrl: 'https://northstar.example/locations/harbor/details',
    matchedTargetIds: ['harbor'],
    matchedUrlIds: ['harbor-url'],
  },
  {
    observationId: 'observation-openai',
    expectedSlotId: 'slot-shared-openai',
    executionId: 'exec-shared',
    usageEdgeId: 'edge-baseline',
    usageEdgeType: 'baseline',
    provider: 'openai',
    queryText: 'roof coating near harbor',
    location: 'Harbor, EX',
    sourceUrl: 'https://northstar.example/shared/guide',
    bridged: false,
    historical: false,
    evidenceComplete: true,
    classification: 'ambiguous',
    normalizedUrl: 'https://northstar.example/shared/guide',
    matchedTargetIds: ['shared-a','shared-b'],
    matchedUrlIds: ['shared-a-url','shared-b-url'],
  },
  {
    observationId: 'observation-openai',
    expectedSlotId: 'slot-shared-openai',
    executionId: 'exec-shared',
    usageEdgeId: 'edge-harbor-shared',
    usageEdgeType: 'target',
    provider: 'openai',
    queryText: 'roof coating near harbor',
    location: 'Harbor, EX',
    sourceUrl: 'https://challenger.example/compare',
    bridged: false,
    historical: false,
    evidenceComplete: true,
    classification: 'external',
    normalizedUrl: 'https://challenger.example/compare',
    matchedTargetIds: [],
    matchedUrlIds: [],
  },
  {
    observationId: 'observation-openai',
    expectedSlotId: 'slot-shared-openai',
    executionId: 'exec-shared',
    usageEdgeId: 'edge-harbor-shared',
    usageEdgeType: 'target',
    provider: 'openai',
    queryText: 'roof coating near harbor',
    location: 'Harbor, EX',
    sourceUrl: 'https://northstar.example/locations/harbor/details',
    bridged: false,
    historical: false,
    evidenceComplete: true,
    classification: 'assigned',
    normalizedUrl: 'https://northstar.example/locations/harbor/details',
    matchedTargetIds: ['harbor'],
    matchedUrlIds: ['harbor-url'],
  },
  {
    observationId: 'observation-openai',
    expectedSlotId: 'slot-shared-openai',
    executionId: 'exec-shared',
    usageEdgeId: 'edge-harbor-shared',
    usageEdgeType: 'target',
    provider: 'openai',
    queryText: 'roof coating near harbor',
    location: 'Harbor, EX',
    sourceUrl: 'https://northstar.example/shared/guide',
    bridged: false,
    historical: false,
    evidenceComplete: true,
    classification: 'ambiguous',
    normalizedUrl: 'https://northstar.example/shared/guide',
    matchedTargetIds: ['shared-a','shared-b'],
    matchedUrlIds: ['shared-a-url','shared-b-url'],
  },
  {
    observationId: 'observation-openai',
    expectedSlotId: 'slot-shared-openai',
    executionId: 'exec-shared',
    usageEdgeId: 'edge-north-shared',
    usageEdgeType: 'target',
    provider: 'openai',
    queryText: 'roof coating near harbor',
    location: 'Harbor, EX',
    sourceUrl: 'https://challenger.example/compare',
    bridged: false,
    historical: false,
    evidenceComplete: true,
    classification: 'external',
    normalizedUrl: 'https://challenger.example/compare',
    matchedTargetIds: [],
    matchedUrlIds: [],
  },
  {
    observationId: 'observation-openai',
    expectedSlotId: 'slot-shared-openai',
    executionId: 'exec-shared',
    usageEdgeId: 'edge-north-shared',
    usageEdgeType: 'target',
    provider: 'openai',
    queryText: 'roof coating near harbor',
    location: 'Harbor, EX',
    sourceUrl: 'https://northstar.example/locations/harbor/details',
    bridged: false,
    historical: false,
    evidenceComplete: true,
    classification: 'sibling',
    normalizedUrl: 'https://northstar.example/locations/harbor/details',
    matchedTargetIds: ['harbor'],
    matchedUrlIds: ['harbor-url'],
  },
  {
    observationId: 'observation-openai',
    expectedSlotId: 'slot-shared-openai',
    executionId: 'exec-shared',
    usageEdgeId: 'edge-north-shared',
    usageEdgeType: 'target',
    provider: 'openai',
    queryText: 'roof coating near harbor',
    location: 'Harbor, EX',
    sourceUrl: 'https://northstar.example/shared/guide',
    bridged: false,
    historical: false,
    evidenceComplete: true,
    classification: 'ambiguous',
    normalizedUrl: 'https://northstar.example/shared/guide',
    matchedTargetIds: ['shared-a','shared-b'],
    matchedUrlIds: ['shared-a-url','shared-b-url'],
  },
  {
    observationId: 'observation-silent',
    expectedSlotId: 'slot-silent',
    executionId: 'exec-silent',
    usageEdgeId: 'edge-north-silent',
    usageEdgeType: 'target',
    provider: 'openai',
    queryText: 'best coating contractor',
    location: null,
    sourceUrl: 'https://northstar.example/locations/north/reviews',
    bridged: false,
    historical: false,
    evidenceComplete: true,
    classification: 'assigned',
    normalizedUrl: 'https://northstar.example/locations/north/reviews',
    matchedTargetIds: ['north'],
    matchedUrlIds: ['north-url'],
  },
]
