import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import {
  CLOUDFLARE_WORKER_BINDINGS,
  DEFAULT_BOT_LIST,
  generateWorkerScript,
  generateWranglerToml,
} from '@ainyc/canonry-integration-cloudflare-worker'
import {
  assertCloudflareArtifactsDoNotContainSecrets,
  deployCloudflareWorker,
  preflightCloudflareWrangler,
  prepareCloudflareWorkerOutputDirectory,
  writeCloudflareWorkerArtifacts,
} from '../src/cloudflare-worker-deploy.js'

const scratchDirectories: string[] = []

function scratch(): string {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'canonry-cloudflare-deploy-test-'))
  scratchDirectories.push(directory)
  return directory
}

afterEach(() => {
  for (const directory of scratchDirectories.splice(0)) {
    fs.rmSync(directory, { recursive: true, force: true })
  }
})

describe('Cloudflare Worker artifacts', () => {
  it('rejects an operator-owned destination during preflight', () => {
    const outputDirectory = path.join(scratch(), 'worker')
    fs.mkdirSync(outputDirectory)
    fs.writeFileSync(path.join(outputDirectory, 'worker.js'), 'operator-owned worker', 'utf-8')

    expect(() => prepareCloudflareWorkerOutputDirectory(outputDirectory))
      .toThrow(/operator-owned artifact/)
  })

  it('writes private, secret-free artifacts and reuses exact files', () => {
    const secrets = {
      bearerToken: 'cnry_cfw_bearer-do-not-print',
      hmacSecret: 'hmac-do-not-print',
    }
    const artifacts = prepareCloudflareWorkerOutputDirectory(path.join(scratch(), 'worker'))
    const contents = {
      workerScript: `export default { fetch() { return env.${CLOUDFLARE_WORKER_BINDINGS.bearerToken} } }`,
      wranglerToml: `[secrets]\nrequired = ["${CLOUDFLARE_WORKER_BINDINGS.hmacSecret}"]\n`,
    }

    assertCloudflareArtifactsDoNotContainSecrets(contents, secrets)
    writeCloudflareWorkerArtifacts(artifacts, contents)
    writeCloudflareWorkerArtifacts(artifacts, contents)

    const combined = fs.readFileSync(artifacts.workerScriptPath, 'utf-8')
      + fs.readFileSync(artifacts.wranglerTomlPath, 'utf-8')
    expect(combined).not.toContain(secrets.bearerToken)
    expect(combined).not.toContain(secrets.hmacSecret)
    expect(fs.statSync(artifacts.workerScriptPath).mode & 0o777).toBe(0o600)
    expect(fs.statSync(artifacts.wranglerTomlPath).mode & 0o777).toBe(0o600)
  })

  it('refuses divergent artifacts and removes files created by the failed write', () => {
    const artifacts = prepareCloudflareWorkerOutputDirectory(path.join(scratch(), 'worker'))
    fs.writeFileSync(artifacts.wranglerTomlPath, 'operator-owned config', 'utf-8')

    expect(() => writeCloudflareWorkerArtifacts(artifacts, {
      workerScript: 'generated worker',
      wranglerToml: 'generated config',
    })).toThrow(/refusing to overwrite/)
    expect(fs.existsSync(artifacts.workerScriptPath)).toBe(false)
    expect(fs.readFileSync(artifacts.wranglerTomlPath, 'utf-8')).toBe('operator-owned config')
  })

  it('atomically upgrades recognizable Canonry-generated artifacts', () => {
    const artifacts = prepareCloudflareWorkerOutputDirectory(path.join(scratch(), 'worker'))
    const initial = {
      workerScript: generateWorkerScript({
        deliveryMode: 'direct-push',
        workerVersion: '1.0.0',
        botList: DEFAULT_BOT_LIST,
      }),
      wranglerToml: generateWranglerToml({
        deliveryMode: 'direct-push',
        sourceId: 'source_test',
        hostname: 'example.com',
        ingestUrl: 'https://canonry.example.net/api/v1/projects/demo/traffic/cloudflare/ingest',
        workerVersion: '1.0.0',
        zoneId: 'zone_test',
      }),
    }
    writeCloudflareWorkerArtifacts(artifacts, initial)

    const upgraded = {
      workerScript: generateWorkerScript({
        deliveryMode: 'direct-push',
        workerVersion: '1.1.0',
        botList: DEFAULT_BOT_LIST,
      }),
      wranglerToml: generateWranglerToml({
        deliveryMode: 'direct-push',
        sourceId: 'source_test',
        hostname: 'example.com',
        ingestUrl: 'https://canonry.example.net/api/v1/projects/demo/traffic/cloudflare/ingest',
        workerVersion: '1.1.0',
        accountId: 'account_test',
        zoneId: 'zone_test',
      }),
    }
    writeCloudflareWorkerArtifacts(artifacts, upgraded)

    expect(fs.readFileSync(artifacts.workerScriptPath, 'utf-8')).toBe(upgraded.workerScript)
    expect(fs.readFileSync(artifacts.wranglerTomlPath, 'utf-8')).toBe(upgraded.wranglerToml)
    expect(fs.readdirSync(artifacts.outputDirectory).sort()).toEqual(['worker.js', 'wrangler.toml'])
  })

  it('upgrades the marker-free Wrangler format generated by the earlier implementation', () => {
    const artifacts = prepareCloudflareWorkerOutputDirectory(path.join(scratch(), 'worker'))
    const workerScript = generateWorkerScript({
      deliveryMode: 'direct-push',
      workerVersion: '1.0.0',
      botList: DEFAULT_BOT_LIST,
    })
    const generatedToml = generateWranglerToml({
      deliveryMode: 'direct-push',
      sourceId: 'source_test',
      hostname: 'example.com',
      ingestUrl: 'https://canonry.example.net/api/v1/projects/demo/traffic/cloudflare/ingest',
      workerVersion: '1.0.0',
      zoneId: 'zone_test',
    })
    const markerFreeToml = generatedToml.slice(generatedToml.indexOf('\n') + 1)
    fs.writeFileSync(artifacts.workerScriptPath, workerScript, { mode: 0o600 })
    fs.writeFileSync(artifacts.wranglerTomlPath, markerFreeToml, { mode: 0o600 })

    writeCloudflareWorkerArtifacts(artifacts, { workerScript, wranglerToml: generatedToml })

    expect(fs.readFileSync(artifacts.wranglerTomlPath, 'utf-8')).toBe(generatedToml)
  })

  it('never replaces operator-owned files or symlinks', () => {
    const root = scratch()
    const artifacts = prepareCloudflareWorkerOutputDirectory(path.join(root, 'worker'))
    fs.writeFileSync(artifacts.workerScriptPath, 'operator-owned worker', 'utf-8')
    const originalToml = 'operator-owned config'
    fs.writeFileSync(artifacts.wranglerTomlPath, originalToml, 'utf-8')

    expect(() => writeCloudflareWorkerArtifacts(artifacts, {
      workerScript: generateWorkerScript({
        deliveryMode: 'direct-push',
        workerVersion: '2.0.0',
        botList: DEFAULT_BOT_LIST,
      }),
      wranglerToml: generateWranglerToml({
        deliveryMode: 'direct-push',
        sourceId: 'source_test',
        hostname: 'example.com',
        ingestUrl: 'https://canonry.example.net/ingest',
        workerVersion: '2.0.0',
      }),
    })).toThrow(/operator-owned artifact/)
    expect(fs.readFileSync(artifacts.workerScriptPath, 'utf-8')).toBe('operator-owned worker')
    expect(fs.readFileSync(artifacts.wranglerTomlPath, 'utf-8')).toBe(originalToml)

    fs.unlinkSync(artifacts.workerScriptPath)
    fs.symlinkSync(path.join(root, 'target.js'), artifacts.workerScriptPath)
    expect(() => prepareCloudflareWorkerOutputDirectory(artifacts.outputDirectory))
      .toThrow(/not a regular file/)
  })

  it('rejects a response that contains either local secret', () => {
    expect(() => assertCloudflareArtifactsDoNotContainSecrets({
      workerScript: 'const leaked = "bearer-secret"',
      wranglerToml: 'safe',
    }, {
      bearerToken: 'bearer-secret',
      hmacSecret: 'hmac-secret',
    })).toThrow(/cleartext secret/)
  })
})

describe('Cloudflare Wrangler deploy', () => {
  it('feature-detects the required deploy flags before setup mutates state', async () => {
    const calls: Array<{ command: string; args: readonly string[]; cwd: string }> = []
    await preflightCloudflareWrangler({
      cwd: '/tmp',
      run: async (command, args, opts) => {
        calls.push({ command, args, cwd: opts.cwd })
        return 'Usage: wrangler deploy [--secrets-file <path>] [--strict]'
      },
    })
    expect(calls).toEqual([{
      command: 'wrangler',
      args: ['deploy', '--help'],
      cwd: '/tmp',
    }])
  })

  it('rejects Wrangler when a required deploy flag is unavailable', async () => {
    await expect(preflightCloudflareWrangler({
      run: async () => 'Usage: wrangler deploy [--strict]',
    })).rejects.toThrow(/--secrets-file/)
  })

  it('passes secrets only through a 0600 temporary file and removes it after success', async () => {
    const root = scratch()
    const wranglerTomlPath = path.join(root, 'wrangler.toml')
    fs.writeFileSync(wranglerTomlPath, 'name = "canonry-test"', 'utf-8')
    const secrets = {
      bearerToken: 'cnry_cfw_bearer-do-not-print',
      hmacSecret: 'hmac-do-not-print',
    }
    let secretsPath = ''

    await deployCloudflareWorker({
      wranglerTomlPath,
      secrets,
      tempRoot: root,
      run: async (command, args, opts) => {
        expect(command).toBe('wrangler')
        expect(args[0]).toBe('deploy')
        expect(args).toContain('--strict')
        expect(args).toContain('--secrets-file')
        expect(args).toContain(path.resolve(wranglerTomlPath))
        expect(opts.cwd).toBe(root)
        expect(args.join(' ')).not.toContain(secrets.bearerToken)
        expect(args.join(' ')).not.toContain(secrets.hmacSecret)

        secretsPath = args[args.indexOf('--secrets-file') + 1]!
        expect(fs.statSync(secretsPath).mode & 0o777).toBe(0o600)
        expect(JSON.parse(fs.readFileSync(secretsPath, 'utf-8'))).toEqual({
          CANONRY_BEARER_TOKEN: secrets.bearerToken,
          CANONRY_HMAC_SECRET: secrets.hmacSecret,
        })
      },
    })

    expect(fs.existsSync(secretsPath)).toBe(false)
    expect(fs.existsSync(path.dirname(secretsPath))).toBe(false)
  })

  it('removes the temporary secret file when Wrangler fails', async () => {
    const root = scratch()
    const wranglerTomlPath = path.join(root, 'wrangler.toml')
    fs.writeFileSync(wranglerTomlPath, 'name = "canonry-test"', 'utf-8')
    let secretsPath = ''

    await expect(deployCloudflareWorker({
      wranglerTomlPath,
      secrets: { bearerToken: 'bearer', hmacSecret: 'hmac' },
      tempRoot: root,
      run: async (_command, args) => {
        secretsPath = args[args.indexOf('--secrets-file') + 1]!
        throw new Error('simulated Wrangler failure')
      },
    })).rejects.toThrow(/simulated Wrangler failure/)

    expect(fs.existsSync(secretsPath)).toBe(false)
    expect(fs.existsSync(path.dirname(secretsPath))).toBe(false)
  })
})
